name: Test Safe

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: curl -L https://images.squarespace-cdn.com/content/v1/5c668d98523958033699cbf3/67cabb72-cdf8-4497-aeee-b668a4e89ae7/IMG_2465%2B2.jpg -o sana-dar-portrait.jpg
      - run: ls -lh sana-dar-portrait.jpg
